ERROR:__main__:Errored: 1 retry happened in running tx: DeliveryTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=cdae67ce key=/Table/57/1/"\x16\xda\xc9@-\xeaF\x00\x8bmd\xa0\x16\xf5z\xc0"/0 pri=0.01949691 epo=0 ts=1635652043.617502000,2 min=1635652040.230030000,0 seq=180} lock=true stat=PENDING rts=1635652040.230030000,0 wto=false gul=1635652040.730030000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#retry_serializable
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 74, in execute_tx
    each_tx_time = tx_ins.delivery_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 290, in delivery_transaction
    m_conn.commit()
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=cdae67ce key=/Table/57/1/"\x16\xda\xc9@-\xeaF\x00\x8bmd\xa0\x16\xf5z\xc0"/0 pri=0.01949691 epo=0 ts=1635652043.617502000,2 min=1635652040.230030000,0 seq=180} lock=true stat=PENDING rts=1635652040.230030000,0 wto=false gul=1635652040.730030000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#retry_serializable

 ]
INFO:__main__:Running Tx DeliveryTxParams successful at the 2 time retry
ERROR:__main__:Errored: 1 retry happened in running tx: DeliveryTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=3843d922 key=/Table/57/1/"U\x112\x81W\xb0D\x00\xaa\x88\x99@\xab\xd8\x02`"/0 pri=0.01776461 epo=0 ts=1635652065.311796000,2 min=1635652061.833324000,0 seq=162} lock=true stat=PENDING rts=1635652061.833324000,0 wto=false gul=1635652062.333324000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#retry_serializable
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 74, in execute_tx
    each_tx_time = tx_ins.delivery_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 290, in delivery_transaction
    m_conn.commit()
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=3843d922 key=/Table/57/1/"U\x112\x81W\xb0D\x00\xaa\x88\x99@\xab\xd8\x02`"/0 pri=0.01776461 epo=0 ts=1635652065.311796000,2 min=1635652061.833324000,0 seq=162} lock=true stat=PENDING rts=1635652061.833324000,0 wto=false gul=1635652062.333324000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#retry_serializable

 ]
INFO:__main__:Running Tx DeliveryTxParams successful at the 2 time retry
INFO:__main__:Running Tx DeliveryTxParams successful at the 2 time retry
ERROR:__main__:Errored: 1 retry happened in running tx: DeliveryTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=5d4d7ec3 key=/Table/57/1/"\x1d\x9f\xd4\xee\x8a\x14J\x00\x8e\xcf\xeawE\nE!"/0 pri=0.00353088 epo=0 ts=1635652137.501083000,2 min=1635652137.476784000,0 seq=143} lock=true stat=PENDING rts=1635652137.476784000,0 wto=false gul=1635652137.976784000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#retry_serializable
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 74, in execute_tx
    each_tx_time = tx_ins.delivery_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 290, in delivery_transaction
    m_conn.commit()
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=5d4d7ec3 key=/Table/57/1/"\x1d\x9f\xd4\xee\x8a\x14J\x00\x8e\xcf\xeawE\nE!"/0 pri=0.00353088 epo=0 ts=1635652137.501083000,2 min=1635652137.476784000,0 seq=143} lock=true stat=PENDING rts=1635652137.476784000,0 wto=false gul=1635652137.976784000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#retry_serializable

 ]
INFO:__main__:Running Tx DeliveryTxParams successful at the 2 time retry
INFO:__main__:Running Tx DeliveryTxParams successful at the 2 time retry
ERROR:__main__:Errored: 1 retry happened in running tx: DeliveryTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=248741c7 key=/Table/57/1/"\xa1\x8e\xbc\x13]\x1eH\x00\x90\xc7^\t\xae\x8fe\xfe"/0 pri=0.02412535 epo=1 ts=1635652234.860076000,2 min=1635652219.795352000,0 seq=171} lock=true stat=PENDING rts=1635652230.060469999,2 wto=false gul=1635652220.295352000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#retry_serializable
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 74, in execute_tx
    each_tx_time = tx_ins.delivery_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 290, in delivery_transaction
    m_conn.commit()
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=248741c7 key=/Table/57/1/"\xa1\x8e\xbc\x13]\x1eH\x00\x90\xc7^\t\xae\x8fe\xfe"/0 pri=0.02412535 epo=1 ts=1635652234.860076000,2 min=1635652219.795352000,0 seq=171} lock=true stat=PENDING rts=1635652230.060469999,2 wto=false gul=1635652220.295352000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#retry_serializable

 ]
INFO:__main__:Running Tx DeliveryTxParams successful at the 2 time retry
ERROR:__main__:Errored: 1 retry happened in running tx: DeliveryTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=00d6e01d key=/Table/57/1/"\x1e\xacoJ\xb8\xbfJ\x00\x8fV7\xa5\\_\xcc\xf8"/0 pri=0.00063800 epo=0 ts=1635652267.243810000,2 min=1635652265.233591000,0 seq=174} lock=true stat=PENDING rts=1635652265.233591000,0 wto=false gul=1635652265.733591000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#retry_serializable
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 74, in execute_tx
    each_tx_time = tx_ins.delivery_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 290, in delivery_transaction
    m_conn.commit()
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): "sql txn" meta={id=00d6e01d key=/Table/57/1/"\x1e\xacoJ\xb8\xbfJ\x00\x8fV7\xa5\\_\xcc\xf8"/0 pri=0.00063800 epo=0 ts=1635652267.243810000,2 min=1635652265.233591000,0 seq=174} lock=true stat=PENDING rts=1635652265.233591000,0 wto=false gul=1635652265.733591000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#retry_serializable

 ]
INFO:__main__:Running Tx DeliveryTxParams successful at the 2 time retry
INFO:__main__:============================ record when total_tx_num reaches 100=====================
INFO:__main__:============================ record when total_tx_num reaches 200=====================
ERROR:__main__:Errored: 1 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635652760.790988000,0 encountered previous write with future timestamp 1635652760.790988000,1 within uncertainty interval `t <= (local=1635652760.792236000,0, global=1635652761.290988000,0)`; observed timestamps: [{2 1635652760.792236000,0} {3 1635652760.790988000,0}]: "sql txn" meta={id=2fa4c4fd pri=0.01951368 epo=0 ts=1635652760.790988000,0 min=1635652760.790988000,0 seq=0} lock=false stat=PENDING rts=1635652760.790988000,0 wto=false gul=1635652761.290988000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 84, in execute_tx
    each_tx_time = tx_ins.related_customer_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 556, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635652760.790988000,0 encountered previous write with future timestamp 1635652760.790988000,1 within uncertainty interval `t <= (local=1635652760.792236000,0, global=1635652761.290988000,0)`; observed timestamps: [{2 1635652760.792236000,0} {3 1635652760.790988000,0}]: "sql txn" meta={id=2fa4c4fd pri=0.01951368 epo=0 ts=1635652760.790988000,0 min=1635652760.790988000,0 seq=0} lock=false stat=PENDING rts=1635652760.790988000,0 wto=false gul=1635652761.290988000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
ERROR:__main__:Errored: 2 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635652766.404320000,0 encountered previous write with future timestamp 1635652766.404320000,1 within uncertainty interval `t <= (local=1635652766.426775000,0, global=1635652766.904320000,0)`; observed timestamps: [{2 1635652766.426775000,0} {3 1635652766.404320000,0}]: "sql txn" meta={id=1e0ce7cd pri=0.00509773 epo=0 ts=1635652766.404320000,0 min=1635652766.404320000,0 seq=0} lock=false stat=PENDING rts=1635652766.404320000,0 wto=false gul=1635652766.904320000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 84, in execute_tx
    each_tx_time = tx_ins.related_customer_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 556, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635652766.404320000,0 encountered previous write with future timestamp 1635652766.404320000,1 within uncertainty interval `t <= (local=1635652766.426775000,0, global=1635652766.904320000,0)`; observed timestamps: [{2 1635652766.426775000,0} {3 1635652766.404320000,0}]: "sql txn" meta={id=1e0ce7cd pri=0.00509773 epo=0 ts=1635652766.404320000,0 min=1635652766.404320000,0 seq=0} lock=false stat=PENDING rts=1635652766.404320000,0 wto=false gul=1635652766.904320000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
ERROR:__main__:Errored: 3 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635652771.231701000,0 encountered previous write with future timestamp 1635652771.231701000,1 within uncertainty interval `t <= (local=1635652771.235641000,0, global=1635652771.731701000,0)`; observed timestamps: [{2 1635652771.235641000,0} {3 1635652771.231701000,0}]: "sql txn" meta={id=797265ab pri=0.00618114 epo=0 ts=1635652771.231701000,0 min=1635652771.231701000,0 seq=0} lock=false stat=PENDING rts=1635652771.231701000,0 wto=false gul=1635652771.731701000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 84, in execute_tx
    each_tx_time = tx_ins.related_customer_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 556, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635652771.231701000,0 encountered previous write with future timestamp 1635652771.231701000,1 within uncertainty interval `t <= (local=1635652771.235641000,0, global=1635652771.731701000,0)`; observed timestamps: [{2 1635652771.235641000,0} {3 1635652771.231701000,0}]: "sql txn" meta={id=797265ab pri=0.00618114 epo=0 ts=1635652771.231701000,0 min=1635652771.231701000,0 seq=0} lock=false stat=PENDING rts=1635652771.231701000,0 wto=false gul=1635652771.731701000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
ERROR:__main__:Errored: 4 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635652778.222896000,0 encountered previous write with future timestamp 1635652778.222896000,1 within uncertainty interval `t <= (local=1635652778.224802000,0, global=1635652778.722896000,0)`; observed timestamps: [{2 1635652778.224802000,0} {3 1635652778.222896000,0}]: "sql txn" meta={id=04c697e5 pri=0.00595627 epo=0 ts=1635652778.222896000,0 min=1635652778.222896000,0 seq=0} lock=false stat=PENDING rts=1635652778.222896000,0 wto=false gul=1635652778.722896000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 84, in execute_tx
    each_tx_time = tx_ins.related_customer_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 556, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635652778.222896000,0 encountered previous write with future timestamp 1635652778.222896000,1 within uncertainty interval `t <= (local=1635652778.224802000,0, global=1635652778.722896000,0)`; observed timestamps: [{2 1635652778.224802000,0} {3 1635652778.222896000,0}]: "sql txn" meta={id=04c697e5 pri=0.00595627 epo=0 ts=1635652778.222896000,0 min=1635652778.222896000,0 seq=0} lock=false stat=PENDING rts=1635652778.222896000,0 wto=false gul=1635652778.722896000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
INFO:__main__:Running Tx RelCustomerTxParams successful at the 5 time retry
INFO:__main__:============================ record when total_tx_num reaches 300=====================
ERROR:__main__:Errored: 1 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635653185.122564000,0 encountered previous write with future timestamp 1635653185.122564000,1 within uncertainty interval `t <= (local=1635653185.123537000,0, global=1635653185.622564000,0)`; observed timestamps: [{2 1635653185.123537000,0} {3 1635653185.122564000,0}]: "sql txn" meta={id=121ee247 pri=0.01018406 epo=0 ts=1635653185.122564000,0 min=1635653185.122564000,0 seq=0} lock=false stat=PENDING rts=1635653185.122564000,0 wto=false gul=1635653185.622564000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 84, in execute_tx
    each_tx_time = tx_ins.related_customer_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 556, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635653185.122564000,0 encountered previous write with future timestamp 1635653185.122564000,1 within uncertainty interval `t <= (local=1635653185.123537000,0, global=1635653185.622564000,0)`; observed timestamps: [{2 1635653185.123537000,0} {3 1635653185.122564000,0}]: "sql txn" meta={id=121ee247 pri=0.01018406 epo=0 ts=1635653185.122564000,0 min=1635653185.122564000,0 seq=0} lock=false stat=PENDING rts=1635653185.122564000,0 wto=false gul=1635653185.622564000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
ERROR:__main__:Errored: 2 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635653190.077608000,0 encountered previous write with future timestamp 1635653190.077608000,1 within uncertainty interval `t <= (local=1635653190.079000000,0, global=1635653190.577608000,0)`; observed timestamps: [{2 1635653190.079000000,0} {3 1635653190.077608000,0}]: "sql txn" meta={id=256a43a0 pri=0.03798096 epo=0 ts=1635653190.077608000,0 min=1635653190.077608000,0 seq=0} lock=false stat=PENDING rts=1635653190.077608000,0 wto=false gul=1635653190.577608000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 84, in execute_tx
    each_tx_time = tx_ins.related_customer_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 556, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635653190.077608000,0 encountered previous write with future timestamp 1635653190.077608000,1 within uncertainty interval `t <= (local=1635653190.079000000,0, global=1635653190.577608000,0)`; observed timestamps: [{2 1635653190.079000000,0} {3 1635653190.077608000,0}]: "sql txn" meta={id=256a43a0 pri=0.03798096 epo=0 ts=1635653190.077608000,0 min=1635653190.077608000,0 seq=0} lock=false stat=PENDING rts=1635653190.077608000,0 wto=false gul=1635653190.577608000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
ERROR:__main__:Errored: 3 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635653197.540434000,0 encountered previous write with future timestamp 1635653197.540434000,1 within uncertainty interval `t <= (local=1635653197.546524000,0, global=1635653198.040434000,0)`; observed timestamps: [{2 1635653197.541447000,0} {3 1635653197.540434000,0} {5 1635653197.546524000,0}]: "sql txn" meta={id=a32569ec pri=0.03294428 epo=0 ts=1635653197.540434000,0 min=1635653197.540434000,0 seq=0} lock=false stat=PENDING rts=1635653197.540434000,0 wto=false gul=1635653198.040434000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 84, in execute_tx
    each_tx_time = tx_ins.related_customer_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 556, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635653197.540434000,0 encountered previous write with future timestamp 1635653197.540434000,1 within uncertainty interval `t <= (local=1635653197.546524000,0, global=1635653198.040434000,0)`; observed timestamps: [{2 1635653197.541447000,0} {3 1635653197.540434000,0} {5 1635653197.546524000,0}]: "sql txn" meta={id=a32569ec pri=0.03294428 epo=0 ts=1635653197.540434000,0 min=1635653197.540434000,0 seq=0} lock=false stat=PENDING rts=1635653197.540434000,0 wto=false gul=1635653198.040434000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
INFO:__main__:Running Tx RelCustomerTxParams successful at the 4 time retry
ERROR:__main__:Errored: 1 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635653249.842318000,0 encountered previous write with future timestamp 1635653249.843060000,0 within uncertainty interval `t <= (local=1635653249.857406000,0, global=1635653250.342318000,0)`; observed timestamps: [{2 1635653249.844429000,0} {3 1635653249.842318000,0} {5 1635653249.857406000,0}]: "sql txn" meta={id=361d5cf2 pri=0.01025544 epo=0 ts=1635653249.842318000,0 min=1635653249.842318000,0 seq=0} lock=false stat=PENDING rts=1635653249.842318000,0 wto=false gul=1635653250.342318000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 84, in execute_tx
    each_tx_time = tx_ins.related_customer_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 556, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635653249.842318000,0 encountered previous write with future timestamp 1635653249.843060000,0 within uncertainty interval `t <= (local=1635653249.857406000,0, global=1635653250.342318000,0)`; observed timestamps: [{2 1635653249.844429000,0} {3 1635653249.842318000,0} {5 1635653249.857406000,0}]: "sql txn" meta={id=361d5cf2 pri=0.01025544 epo=0 ts=1635653249.842318000,0 min=1635653249.842318000,0 seq=0} lock=false stat=PENDING rts=1635653249.842318000,0 wto=false gul=1635653250.342318000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
ERROR:__main__:Errored: 2 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635653256.845983000,0 encountered previous write with future timestamp 1635653256.845983000,1 within uncertainty interval `t <= (local=1635653256.866414000,0, global=1635653257.345983000,0)`; observed timestamps: [{2 1635653256.848384000,0} {3 1635653256.845983000,0} {5 1635653256.866414000,0}]: "sql txn" meta={id=bd99c9ec pri=0.00562742 epo=0 ts=1635653256.845983000,0 min=1635653256.845983000,0 seq=0} lock=false stat=PENDING rts=1635653256.845983000,0 wto=false gul=1635653257.345983000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 84, in execute_tx
    each_tx_time = tx_ins.related_customer_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 556, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635653256.845983000,0 encountered previous write with future timestamp 1635653256.845983000,1 within uncertainty interval `t <= (local=1635653256.866414000,0, global=1635653257.345983000,0)`; observed timestamps: [{2 1635653256.848384000,0} {3 1635653256.845983000,0} {5 1635653256.866414000,0}]: "sql txn" meta={id=bd99c9ec pri=0.00562742 epo=0 ts=1635653256.845983000,0 min=1635653256.845983000,0 seq=0} lock=false stat=PENDING rts=1635653256.845983000,0 wto=false gul=1635653257.345983000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
INFO:__main__:Running Tx RelCustomerTxParams successful at the 3 time retry
ERROR:__main__:Errored: 1 retry happened in running tx: PaymentTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_PUSHER_ABORTED): "sql txn" meta={id=d9363b5d key=/Table/54/1/5 pri=0.08198717 epo=0 ts=1635653331.913821000,0 min=1635653326.911697000,0 seq=1} lock=true stat=ABORTED rts=1635653326.911697000,0 wto=false gul=1635653327.411697000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#abort_reason_pusher_aborted
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 72, in execute_tx
    each_tx_time = tx_ins.payment_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 197, in payment_transaction
    (payment_amount, c_w_id, c_d_id))
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_PUSHER_ABORTED): "sql txn" meta={id=d9363b5d key=/Table/54/1/5 pri=0.08198717 epo=0 ts=1635653331.913821000,0 min=1635653326.911697000,0 seq=1} lock=true stat=ABORTED rts=1635653326.911697000,0 wto=false gul=1635653327.411697000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#abort_reason_pusher_aborted

 ]
INFO:__main__:Running Tx PaymentTxParams successful at the 2 time retry
INFO:__main__:============================ record when total_tx_num reaches 400=====================
INFO:__main__:============================ record when total_tx_num reaches 500=====================
INFO:__main__:============================ record when total_tx_num reaches 600=====================
INFO:__main__:============================ record when total_tx_num reaches 700=====================
ERROR:__main__:Errored: 1 retry happened in running tx: StockLevelTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635654547.549335000,0 encountered previous write with future timestamp 1635654547.672973000,0 within uncertainty interval `t <= (local=1635654548.049335000,0, global=1635654548.049335000,0)`; observed timestamps: [{1 1635654548.689498000,0} {2 1635654548.689533000,0} {3 1635654547.549335000,0} {4 1635654548.528610000,0} {5 1635654547.549999000,0}]: "sql txn" meta={id=e636fc9c pri=0.00422122 epo=0 ts=1635654547.549335000,0 min=1635654547.549335000,0 seq=0} lock=false stat=PENDING rts=1635654547.549335000,0 wto=false gul=1635654548.049335000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 78, in execute_tx
    each_tx_time = tx_ins.stock_level_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 381, in stock_level_transaction
    ''', (w_id, d_id, n - l, n, threshold))
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635654547.549335000,0 encountered previous write with future timestamp 1635654547.672973000,0 within uncertainty interval `t <= (local=1635654548.049335000,0, global=1635654548.049335000,0)`; observed timestamps: [{1 1635654548.689498000,0} {2 1635654548.689533000,0} {3 1635654547.549335000,0} {4 1635654548.528610000,0} {5 1635654547.549999000,0}]: "sql txn" meta={id=e636fc9c pri=0.00422122 epo=0 ts=1635654547.549335000,0 min=1635654547.549335000,0 seq=0} lock=false stat=PENDING rts=1635654547.549335000,0 wto=false gul=1635654548.049335000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
INFO:__main__:Running Tx StockLevelTxParams successful at the 2 time retry
ERROR:__main__:Errored: 1 retry happened in running tx: StockLevelTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635654602.442858000,0 encountered previous write with future timestamp 1635654602.806042000,0 within uncertainty interval `t <= (local=1635654602.942858000,0, global=1635654602.942858000,0)`; observed timestamps: [{1 1635654603.840264000,0} {2 1635654603.532114000,0} {3 1635654602.442858000,0} {4 1635654603.343399000,0} {5 1635654602.443853000,0}]: "sql txn" meta={id=31a6b5f3 pri=0.02679904 epo=0 ts=1635654602.442858000,0 min=1635654602.442858000,0 seq=0} lock=false stat=PENDING rts=1635654602.442858000,0 wto=false gul=1635654602.942858000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 78, in execute_tx
    each_tx_time = tx_ins.stock_level_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 381, in stock_level_transaction
    ''', (w_id, d_id, n - l, n, threshold))
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635654602.442858000,0 encountered previous write with future timestamp 1635654602.806042000,0 within uncertainty interval `t <= (local=1635654602.942858000,0, global=1635654602.942858000,0)`; observed timestamps: [{1 1635654603.840264000,0} {2 1635654603.532114000,0} {3 1635654602.442858000,0} {4 1635654603.343399000,0} {5 1635654602.443853000,0}]: "sql txn" meta={id=31a6b5f3 pri=0.02679904 epo=0 ts=1635654602.442858000,0 min=1635654602.442858000,0 seq=0} lock=false stat=PENDING rts=1635654602.442858000,0 wto=false gul=1635654602.942858000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
INFO:__main__:Running Tx StockLevelTxParams successful at the 2 time retry
INFO:__main__:============================ record when total_tx_num reaches 800=====================
INFO:__main__:============================ record when total_tx_num reaches 900=====================
INFO:__main__:============================ using file /opt/project_files/xact_files_A/37.txt=====================
INFO:__main__:{'NewOrderTxParams': 360, 'TopBalanceTxParams': 11, 'PopItemTxParams': 7, 'PaymentTxParams': 471, 'DeliveryTxParams': 38, 'OrderStatusTxParams': 4, 'RelCustomerTxParams': 4, 'StockLevelTxParams': 6}
INFO:__main__:============================ total time used: 2785.1894311904907 second =====================
