ERROR:__main__:Errored: 1 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635679098.961884000,0 encountered previous write with future timestamp 1635679098.961884000,1 within uncertainty interval `t <= (local=1635679098.970377000,0, global=1635679099.461884000,0)`; observed timestamps: [{1 1635679098.962799000,0} {4 1635679098.961884000,0} {5 1635679098.970377000,0}]: "sql txn" meta={id=b53c29c5 pri=0.01358599 epo=0 ts=1635679098.961884000,0 min=1635679098.961884000,0 seq=0} lock=false stat=PENDING rts=1635679098.961884000,0 wto=false gul=1635679099.461884000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 64, in run_tx
    each_tx_time = operation(m_conn)
  File "cockroachDB_driver.py", line 142, in <lambda>
    lambda l_conn: m_tx_ins.related_customer_transaction(l_conn, m_params))
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 551, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635679098.961884000,0 encountered previous write with future timestamp 1635679098.961884000,1 within uncertainty interval `t <= (local=1635679098.970377000,0, global=1635679099.461884000,0)`; observed timestamps: [{1 1635679098.962799000,0} {4 1635679098.961884000,0} {5 1635679098.970377000,0}]: "sql txn" meta={id=b53c29c5 pri=0.01358599 epo=0 ts=1635679098.961884000,0 min=1635679098.961884000,0 seq=0} lock=false stat=PENDING rts=1635679098.961884000,0 wto=false gul=1635679099.461884000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
INFO:__main__:Running Tx RelCustomerTxParams successful at the 2 time retry
INFO:__main__:============================ record when total_tx_num reaches 100=====================
INFO:__main__:============================ record when total_tx_num reaches 200=====================
ERROR:__main__:Errored: 1 retry happened in running tx: NewOrderTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_PUSHER_ABORTED): "sql txn" meta={id=b41bc883 key=/Table/55/1/10/6 pri=0.01783087 epo=0 ts=1635679960.877839000,0 min=1635679959.876135000,0 seq=62} lock=true stat=ABORTED rts=1635679959.876135000,0 wto=false gul=1635679960.376135000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#abort_reason_pusher_aborted
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 64, in run_tx
    each_tx_time = operation(m_conn)
  File "cockroachDB_driver.py", line 105, in <lambda>
    lambda l_conn: m_tx_ins.new_order_transaction(l_conn, m_params))
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 132, in new_order_transaction
    cur.execute("SELECT W_TAX FROM warehouse WHERE W_ID = %s", [w_id])
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_PUSHER_ABORTED): "sql txn" meta={id=b41bc883 key=/Table/55/1/10/6 pri=0.01783087 epo=0 ts=1635679960.877839000,0 min=1635679959.876135000,0 seq=62} lock=true stat=ABORTED rts=1635679959.876135000,0 wto=false gul=1635679960.376135000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#abort_reason_pusher_aborted

 ]
INFO:__main__:Running Tx NewOrderTxParams successful at the 2 time retry
ERROR:__main__:Errored: 1 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635680298.743605000,0 encountered previous write with future timestamp 1635680298.743746000,0 within uncertainty interval `t <= (local=1635680298.753893000,0, global=1635680299.243605000,0)`; observed timestamps: [{1 1635680298.744771000,0} {2 1635680298.753893000,0} {4 1635680298.743605000,0}]: "sql txn" meta={id=6d738c24 pri=0.06143888 epo=0 ts=1635680298.743605000,0 min=1635680298.743605000,0 seq=0} lock=false stat=PENDING rts=1635680298.743605000,0 wto=false gul=1635680299.243605000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 64, in run_tx
    each_tx_time = operation(m_conn)
  File "cockroachDB_driver.py", line 142, in <lambda>
    lambda l_conn: m_tx_ins.related_customer_transaction(l_conn, m_params))
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 551, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635680298.743605000,0 encountered previous write with future timestamp 1635680298.743746000,0 within uncertainty interval `t <= (local=1635680298.753893000,0, global=1635680299.243605000,0)`; observed timestamps: [{1 1635680298.744771000,0} {2 1635680298.753893000,0} {4 1635680298.743605000,0}]: "sql txn" meta={id=6d738c24 pri=0.06143888 epo=0 ts=1635680298.743605000,0 min=1635680298.743605000,0 seq=0} lock=false stat=PENDING rts=1635680298.743605000,0 wto=false gul=1635680299.243605000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
INFO:__main__:Running Tx RelCustomerTxParams successful at the 2 time retry
INFO:__main__:============================ record when total_tx_num reaches 300=====================
ERROR:__main__:Errored: 1 retry happened in running tx: NewOrderTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_PUSHER_ABORTED): "sql txn" meta={id=9933c83f key=/Table/55/1/10/6 pri=0.01448668 epo=0 ts=1635680546.266726000,0 min=1635680545.265833000,0 seq=86} lock=true stat=ABORTED rts=1635680545.265833000,0 wto=false gul=1635680545.765833000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#abort_reason_pusher_aborted
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 64, in run_tx
    each_tx_time = operation(m_conn)
  File "cockroachDB_driver.py", line 105, in <lambda>
    lambda l_conn: m_tx_ins.new_order_transaction(l_conn, m_params))
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 132, in new_order_transaction
    cur.execute("SELECT W_TAX FROM warehouse WHERE W_ID = %s", [w_id])
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_PUSHER_ABORTED): "sql txn" meta={id=9933c83f key=/Table/55/1/10/6 pri=0.01448668 epo=0 ts=1635680546.266726000,0 min=1635680545.265833000,0 seq=86} lock=true stat=ABORTED rts=1635680545.265833000,0 wto=false gul=1635680545.765833000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#abort_reason_pusher_aborted

 ]
INFO:__main__:Running Tx NewOrderTxParams successful at the 2 time retry
INFO:__main__:============================ record when total_tx_num reaches 400=====================
INFO:__main__:============================ record when total_tx_num reaches 500=====================
INFO:__main__:============================ record when total_tx_num reaches 600=====================
INFO:__main__:============================ record when total_tx_num reaches 700=====================
INFO:__main__:============================ record when total_tx_num reaches 800=====================
INFO:__main__:============================ record when total_tx_num reaches 900=====================
INFO:__main__:============================ using file /opt/project_files/xact_files_A/38.txt=====================
INFO:__main__:{'NewOrderTxParams': 692, 'PaymentTxParams': 145, 'DeliveryTxParams': 35, 'StockLevelTxParams': 8, 'PopItemTxParams': 5, 'OrderStatusTxParams': 6, 'RelCustomerTxParams': 5, 'TopBalanceTxParams': 5}
INFO:__main__:{'NewOrderTxParams': 692, 'PaymentTxParams': 145, 'DeliveryTxParams': 35, 'StockLevelTxParams': 8, 'PopItemTxParams': 5, 'OrderStatusTxParams': 6, 'RelCustomerTxParams': 5, 'TopBalanceTxParams': 5}
INFO:__main__:============================ total time used: 2303.0959379673004 second =====================
